INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Jonathan', 'Hurtado', 'jhon@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_category (name, created_At) VALUES ('Tarjetas gráficas', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Periféricos', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Portátiles', NOW());

INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Teclado Gamer Ninja Black Noir, RGB, Switch Membrana, ABNT2, Black, TC-GN-BKNR', 120.5, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z', 'Mejora tu rendimiento en los juegos con el teclado gamer Ninja Black Noir, un teclado diseñado especialmente para jugadores que buscan un teclado silencioso para usar durante las partidas, combinando comodidad y funcionalidades.
ILUMINACIÓN
El Black Noir cuenta con 7 modos de iluminación, con opciones para cambiar el brillo y la velocidad.
FUNCIONALIDAD
El Black Noir utiliza la funcionalidad plug-and-play, por lo que está listo para usar tan pronto como lo conectes a una computadora compatible o a un portátil. ¡Fácil y práctico!
SWITCH MEMBRANA
El teclado Gamer Ninja Black Noir es un teclado de entrada con teclas de membrana. Ideal para tareas diarias y juegos casuales. Cuenta con RGB para darle un toque más elegante a tu setup.', 'https://img.terabyteshop.com.br/produto/p/teclado-gamer-ninja-black-noir-rgb-switch-membrana-abnt2-black-tc-gn-bknr_148766.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Teclado Logitech K480, Sem Fio, Bluetooth, ANSI, Com Suporte Para Tablet E Smartphone, Black', 319.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Teclado Logitech K480, Sem Fio, Bluetooth, ANSI, Com Suporte Para Tablet E Smartphone, Black', 'https://img.terabyteshop.com.br/produto/p/teclado-logitech-k480-sem-fio-bluetooth-ansi-com-suporte-para-tablet-e-smartphone-black-920-006348_145647.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Tarjeta De Video Gigabyte NVIDIA GeForce RTX 4060 EAGLE OC, 8GB, GDDR6, DLSS, Ray Tracing', 3250.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', '', 'https://img.terabyteshop.com.br/produto/p/placa-de-video-gigabyte-nvidia-geforce-rtx-4060-eagle-oc-8gb-gddr6-dlss-ray-tracing-gv-n4060eagle-oc-8gd_172916.png');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Tarjeta De Video Galax NVIDIA GeForce RTX 3050 EX (1-Click OC), LHR, 8GB, GDDR6, DLSS, Ray Tracing, 35NSL8M', 2200.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', '', 'https://img.terabyteshop.com.br/produto/p/placa-de-video-galax-geforce-rtx-3050-ex-1-click-oc-lhr-8gb-gddr6-dlss-ray-tracing-35nsl8md6yex_175771.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Teclado Gamer Mecânico Redragon Lakshmi, Rainbow, Switch Brown, ABNT2, 60%, Black, K606R PT-BROWN', 300.99, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'El Redragon LAKSHMI reúne lo mejor en un teclado para tu configuración, ofrece un rendimiento profesional, evita los doble clics y tiene el doble de vida útil en comparación con un teclado mecánico convencional. Es el teclado perfecto para aquellos que buscan una excelente mejora para su configuración.', 'https://img.terabyteshop.com.br/produto/p/teclado-gamer-mecanico-redragon-lakshmi-rainbow-switch-brown-abnt2-60-black-k606r-pt-brown_167733.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Lenovo IdeaPad, 20 GB de RAM, SSD de 1 TB, procesador AMD de doble núcleo, pantalla antirreflejos HD de 15.6 pulgadas, batería de larga duración de hasta 9.5 horas', 3350.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Procesador: procesador AMD Athlon de 2.3 GHz (caché de 4M, hasta 3.2 GHz, 2 núcleos) para un rendimiento rápido y rápido.
Memoria y almacenamiento: 20 GB de RAM de alto ancho de banda para ejecutar sin problemas múltiples aplicaciones y pestañas del navegador a la vez. El disco duro es una unidad de estado sólido (SSD) PCIe de 1 TB con disco de inicio eMMC de 128 GB que permite un arranque rápido y transferencia de datos.
Pantalla: pantalla antirreflejante HD de 15.6 pulgadas (1366 x 768), retroiluminación LED de bajo consumo que te da más área de visualización y menos desorden, en una pantalla HD cristalina.', 'https://m.media-amazon.com/images/I/81oyXsmzx2L._AC_SL1500_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('SAMSUNG Computadora portátil Galaxy Book3 de 15.6 pulgadas, procesador Intel Core i7-1355U de 13ª generación, 16 GB, 512 GB, delgada y ligera, pantalla FHD, lector de huellas dactilares, cámara web HD, modelo 2023, NP750XFG-KB2US, plata', 6870.90, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Espacio de visualización ampliable con 2ª pantalla: aumenta tu espacio de trabajo en tu PC Galaxy Book3 conectando tu Tab como una segunda pantalla;****** Los dispositivos se emparejan fácilmente para darte más espacio para trabajar o jugar al máximo: dos pantallas son mejores que una
Diseño delgado, ligero y premium: agárralo y listo; con un diseño delgado y ligero que está hecho para moverse contigo, Galaxy Book3 siempre está listo para ayudarte a tener el día en cualquier lugar que vayas
Gran pantalla/entretenimiento: di adiós a lo normal con una hermosa pantalla que saca lo mejor en todo lo que haces; nítida, brillante y hermosa, tu pantalla Full HD cuenta con toda la calidad que esperas de una pantalla Galaxy', 'https://m.media-amazon.com/images/I/41x6QZ2gwyL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Acer Nitro 17 - Laptop para juegos | CPU AMD Ryzen 7 7840HS Octa-Core | GPU NVIDIA GeForce RTX 4050 | Pantalla IPS FHD de 17.3 pulgadas | DDR5 de 16 GB | SSD de 1 TB Gen 4 | Wi-Fi 6E | KB retroiluminado RGB | AN17-41-R6L9', 8550.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Acelera a toda velocidad con la laptop para juegos Acer Nitro 17 con los últimos procesadores AMD Ryzen serie 7000 y la tecnología DLSS 3 de NVIDIA, ya sea jugando casualmente o subiendo en línea. La pantalla FHD de 17.3 pulgadas perfecta con frecuencias de actualización de 165 Hz proporciona una experiencia de visualización inmersiva mientras que la refrigeración de próxima generación, un teclado RGB de 4 zonas y el software NitroSense te permiten tomar el control del campo de juego.', 'https://m.media-amazon.com/images/I/711+0tgn+6L._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Acer Nitro 5 Laptop para juegos | Intel 12.ª generación i7-12650H | GPU NVIDIA GeForce RTX 4060 para portátil | Pantalla IPS FHD de 15.6 pulgadas | DDR5 de 16 GB | SSD de 1 TB Gen 4 | Killer Wi-Fi 6 | KB retroiluminado RGB | AN515-58-781P', 9050.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Más allá de lo rápido: la GPU para portátil NVIDIA GeForce RTX 4060 es más que rápida para jugadores y creadores. Están impulsados por la arquitectura ultra eficiente NVIDIA Ada Lovelace que ofrece un salto cuántico tanto en rendimiento como en gráficos impulsados por IA.', 'https://m.media-amazon.com/images/I/71Wkd-uyvnL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('ASUS TUF Gaming A17 (2023) Laptop para juegos, pantalla FHD de 17.3 pulgadas de 144 Hz, GeForce RTX 4050, AMD Ryzen 9 7940HS, 16GB DDR5, 1TB PCIe 4.0 SSD, Wi-Fi 6, Windows 11, FA707XU-EH94', 8700.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Listo para cualquier cosa: salta directamente a la acción con Windows 11, procesador AMD Ryzen 9 7940HS y la GPU para portátil NVIDIA GeForce RTX 4050 a 140 W Max TGP.
Memoria y almacenamiento rápidos: multitarea rápidamente con 16 GB de memoria DDR5-4800MHz y acelera los tiempos de carga con 1 TB de PCIe 4.0. Actualizar el almacenamiento es muy fácil con la ranura SSD adicional.', 'https://m.media-amazon.com/images/I/519tAJTfFXL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('GIGABYTE G5 KF: 15.6" FHD 1920x1080 144Hz, NVIDIA GeForce RTX 4060 GPU, Intel Core i5-12500H, 8GB DDR4 RAM, 512G SSD, Win11 Home (G5 KF-E3US333SH) Negro', 5950.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Serie NVIDIA GeForce RTX 40: GPU para portátil NVIDIA GeForce RTX 4060
Intel 12ª generación Ready: Procesador Intel Core i5-12500H de 12ª generación de 4.5 GHz
DDR4 3200 8GB1 (8GB), almacenamiento 512G (SSD Gen4 M.2)
Pantalla de vanguardia: 15.6" FHD 1920x1080, 144Hz', 'https://m.media-amazon.com/images/I/71tgmKoXApL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Acer Aspire 3 A315-24P-R7VH - Laptop delgada, pantalla IPS Full HD de 15.6 pulgadas, procesador AMD Ryzen 3 7320U de cuatro núcleos, gráficos AMD Radeon, 8 GB LPDDR5, SSD NVMe de 128 GB, Wi-Fi 6, Windows 11 Home en modo S', 3850.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Diseño con propósito: Viaja con facilidad y luce genial haciéndolo con el diseño delgado y ligero de Aspire.
Rendimiento listo para usar: el Aspire 3 está listo para usar con el último procesador AMD Ryzen 3 7320U con gráficos Radeon, ideal para toda la familia, con rendimiento y productividad en el núcleo.
Visiblemente impresionante: Experimente detalles nítidos y colores nítidos en la pantalla IPS Full HD de 15,6" con relación de aspecto 16:9 y biseles estrechos.', 'https://m.media-amazon.com/images/I/61gKkYQn6lL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('hp Laptop Essential 15 más reciente, 16 GB de RAM, 640 GB (128 GB SSD+512 GB USB), pantalla antirreflejos de 15.6 pulgadas, procesador Intel Quad-Core, Office 365 1 año, batería de hasta 11 horas, tipo C, carga rápida, Win11S, JVQ MP
', 3350.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Precio perfecto. Benefíciate de capacidades multitarea mejoradas con 16 GB de RAM DDR4, que te ayuda a realizar tareas informáticas diarias para que puedas mantenerte en tu flujo. 128 GB SSD+ 512 GB de almacenamiento USB, que ofrece un rendimiento hasta 15 veces más rápido en comparación con los discos duros tradicionales, lo cual es ideal para PC ultracompactas que necesitan una solución de almacenamiento interno de alto rendimiento y eficiencia energética.', 'https://m.media-amazon.com/images/I/71ASAtN3OZL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('HP 2023 Laptop ultral ligera HD de 14 pulgadas, procesador Intel Celeron de cuatro núcleos, 16 GB de RAM, 320 GB (64 GB eMMC+ 256 GB SD), Wi-Fi, hasta 11 horas, Windows 11 S + 1 año Office 365 + HubxcelAccesorio, blanco', 2250.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Pantalla LED HD de 14.0 pulgadas: diagonal de 14.0 pulgadas, HD (1366 x 768), micro-borde, BrightView, 220 nits, pantalla NTSC del 45%. Ideal para el hogar, estudiantes, profesionales, pequeñas empresas, educación escolar y empresas comerciales. Clase en línea, aula de Google, Aprendizaje remoto, Zoom Ready.', 'https://m.media-amazon.com/images/I/71tqRwvrlLL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('TOPOSH Portátil para niños de 10.1 pulgadas compatible con Windows 10, computadora portátil 4 GB de RAM+64 GB SSD Intel Celeron N3350 gráficos de doble núcleo 1.1 GHz con teclado de EE. UU. WiFi Bluetooth-Verde', 1200.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Sistema Windows: la mini computadora portátil TOPOSH PC es compatible con el sistema operativo Windows 10 Home, con una pantalla de 10.1 pulgadas que tiene buen brillo y resolución FullHD de 1366 x 768p
MEMORIAS: La computadora portátil TOPOSH tiene 4 GB de memoria RAM y 64 GB de almacenamiento. Garantiza un funcionamiento suave y una multitarea estable utilizando la sensación, satisfaciendo las necesidades de la oficina diaria y el estudio. Puede elegir diferentes configuraciones según sus necesidades', 'https://m.media-amazon.com/images/I/61UBi+n+EWL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('maxsun GeForce GT 730 - Tarjeta gráfica de vídeo GPU de 4 GB para PC de 128 bits DDR3 ITX diseño PCI Express DVI-I, HDMI, VGA', 740.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'GPU GeForce GT 730. 384 núcleos de procesador CUDA. Bus de memoria DDR3 de 64 bits de 4 GB. Reloj del motor: 902 MHz. Reloj de memoria: 1600 MHz. PCI Express 2.0 X16
Tamaño del factor de forma ITX perfecto en la mayoría de las cajas de computadora de PC
Compatible con pantalla triple simultánea, 3 x Monitores compatibles: HDMI, DVI, VGA', 'https://m.media-amazon.com/images/I/610EMpP+PKS._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('XFX Speedster SWFT 210 Radeon RX 6600 CORE - Tarjeta gráfica para juegos con 8 GB GDDR6 HDMI 3xDP, AMD RDNA 2 RX-66XL8LFDQ', 1880.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Velocidad de memoria: 14 GBPS. Requisito mínimo de fuente de alimentación: 550 W
Chipset: AMD RX 6600
Memoria: la arquitectura GDDR6 AMD RDNA 2 de 8 GB eleva y unifica los juegos
Boost Clock: hasta 2491 MHz. Evita el uso de software no oficial
Refrigeración: ventilador dual XFX Speedster SWFT210', 'https://m.media-amazon.com/images/I/71gv2U3IPZL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('SAPLOS Radeon RX 550 - Tarjeta gráfica de perfil bajo, 4 GB, GDDR5, 128 bits, VGA DVI-D HDMI, tarjeta de video para juegos de PC, pantalla 4K, GPU de computadora, factor de forma pequeño SFF, DirectX 12, baja potencia', 1250.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', '4 GB/GDDR5/128 bits: la tarjeta de video de 0.14 oz es potente para la arquitectura Polaris con proceso de 14 nm, con procesadores de 512 flujos y memoria GDDR5 de 128 bits de 4 GB, velocidad de memoria de 6 Gbps. La frecuencia básica es de 1183 MHz.
✔️Fácil de instalar: la tarjeta gráfica de pice es adecuada para fundas Sff, Mini o MidTower que ahorran espacio en la funda. Simplemente retire el puerto VGA y cambie el soporte de perfil bajo es compatible con la placa base ITX o ATX convencional. El paquete incluye un par de soportes. Si falta, ponte en contacto con nosotros por favor.)', 'https://m.media-amazon.com/images/I/51Wkvytc1aL._AC_SR160,160_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('ARDIYES Tarjetas gráficas RX 580 8G (con ventiladores RGB), tarjeta GPU para juegos, real 8GB, 2048SP, GDDR5, 256 bits, tarjeta de video para juegos de PC, 3XDP)', 1750.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'RX 580 8G es una GPU para juegos convencional construida sobre el proceso de 14 nm y basada en el procesador gráfico Polaris 20, en su variante Polaris 20 XTX, la tarjeta de video es compatible con DirectX 12. Esto asegura que todos los juegos modernos se ejecutarán en este RX 580. La gpu ha equipado con 2048SP y 8GB de memoria GDDR5 con una memoria de 1750 MHz (8 GB), características para ofrecer las experiencias de juego más rápidas, fluidas y eficientes en el consumo de energía para los usuarios de computadoras.', 'https://m.media-amazon.com/images/I/51Da4f9UMbL._AC_SR160,160_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('maxsun AMD Radeon RX 550 4GB GDDR5 ITX Computadora PC Gaming Video Tarjeta Gráfica GPU 128-Bit DirectX 12 PCI Express X16 3.0 DVI-D Dual Link, HDMI, DisplayPort', 1750.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Chipset AMD Radeon RX 550, PCB plateado y todos los condensadores sólidos proporcionan una temperatura más baja, mayor eficiencia y estabilidad
Ventilador único de 3.5 in que proporciona poco ruido y un gran flujo de aire para tu GPU
GPU Boost Clock / Velocidad de memoria: hasta 1183 MHz / 4 GB GDDR5 / 6000 MHz de memoria, procesadores de flujo 512, perfecto para trabajo 3D CAD/CAM, edición de video y fotos, videojuegos @1080p
Soporte: DirectX 12, Shader Model 5.0, OpenGL 4.6/4.5, decodificación de video 4K', 'https://m.media-amazon.com/images/I/51b7eL+1TxL._AC_SR320,320_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('DIERYA Gaming Mouse, Wired Mouse with Honeycomb, Up to 12800 DPI, 6 Programmable Macro Buttons, Software Support for Custom Key Bindings and RGB Settings for Windows 7/8/10/XP Vista Linux-White
', 168.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', '【High Precision Optical Sensor】This is a great mouse for gamers and typists200-12800DPI gaming-grade sensor responds precisely to movements125-1000Hz Polling rateCustomize sensitivity settings for the best gaming and design experience.
【Adjustable Light band】Lightband RGB mouse has 13 excellent & gorgeous effects with 16.8 million colors customizable and adjustableThe lights can change with the rhythm of game sound and music.
【75G Ultra-Lightweight Design】The honeycomb structure on the top and bottom significantly reduces the overall weight of the mouse, Unique hollow design, so that the hand holding the mouse for a long time is not easy to sweat.And the ultra-flexible braided cable is so light it produces a drag-free wireless feel.', 'https://m.media-amazon.com/images/I/61DP9FeE6KL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Mouse para juegos Razer DeathAdder Essential: Sensor óptico 6400 DPI, 5 botones programables, interruptores mecánicos, agarres laterales de goma. Negro clásico.', 270.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'El fabricante #1 de periféricos para videojuegos con más ventas en los Estados Unidos. Fuente: The NPD Group, Inc. EE.UU. -
Sensor óptico de alta precisión de 6,400 DPI: Ofrece ajuste de sensibilidad sobre la marcha a través de botones DPI dedicados (reprogramables) para juego y para trabajos creativos.
Interruptores mecánicos duraderos: Soporta hasta 10 millones de clics.
Rueda de desplazamiento estriada de goma para una máxima precisión: Las pequeñas protuberancias táctiles aumentan el agarre y ayudan con un desplazamiento más controlado en situaciones de juego muy desafiantes.', 'https://m.media-amazon.com/images/I/8189uwDnMkL._AC_UY218_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Alfombrilla de ratón RGB LED, alfombrilla de ratón grande, alfombrilla de ratón LED y alfombrilla de ratón grande', 150.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Esta alfombrilla para ratón para juegos cuenta con 14 modos de iluminación: incluye modo de iluminación de respiración dinámica y modo de iluminación estática monocromática, haciendo que tu ambiente de juego sea más cálido y atmosférico. También tiene una función de memoria de apagado, que puede memorizar el modo que seleccionaste la última vez.', 'https://images-na.ssl-images-amazon.com/images/I/61HyJYD+TeS._AC_UL232_SR232,232_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Redragon M612 Predator RGB - Ratón para juegos con cable de 8000 DPI con 11 botones programables y 5 modos retroiluminados', 210.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Pentakill, 5 niveles de DPI: equipado con 5 niveles de DPI redefinibles (por defecto como: 500/1000/2000/3000/4000), fácil de cambiar entre diferentes necesidades de juego. La demanda dedicada de opciones de DPI entre 500-8000 también está disponible para ser procesada por software.
Cualquier botón es reasignable: 11 botones programables son editables con teclas tácticas personalizables en cualquier juego o trabajo que estés comprometido. 1 disparo rápido + 2 botones macro laterales que te ofrecen una mejor experiencia de juego y trabajo.', 'https://images-na.ssl-images-amazon.com/images/I/61vF4LdktpL._AC_UL232_SR232,232_.jpg');
INSERT INTO tb_product (name, price, date, description, img_url) VALUES ('Redragon Paquete de mouse para juegos K631 PRO 60% con teclado M612', 470.0, TIMESTAMP WITH TIME ZONE '2020-07-14T10:00:00Z', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://m.media-amazon.com/images/I/415nrFFJJcL._SS150_.jpg');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 2);
